#     ___               __              
#    /   |  ____  _____/ /_  ____  _____
#   / /| | / __ \/ ___/ __ \/ __ \/ ___/
#  / ___ |/ / / / /__/ / / / /_/ / /    
# /_/  |_/_/ /_/\___/_/ /_/\____/_/     
#                                                       
# An open-source project by Mykyta (TechToolbox)
# https://mykyta.tk/
#
# Ahoy, matey! You've arrived at the configuration file, where things get a bit scary. 
# Every single thing within this plugin is customizable (at least I tried to make it that way),
# so every message and plugin module can be modified here. If you would like to report a bug
# or suggest a feature, make sure to add an issue on the GitHub page for this plugin!
# GitHub URL: https://github.com/nkomarn/Anchor/issues

values:
  # The type of block that is used for Anchors (set to a value from this list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
  block: BEACON
  # Display name of the Anchor block item
  name: "&6Anchor"
  # Lores that will display on the Anchor block item
  lore: 
    - "&7Keeps your chunks loaded even when you're gone!"
  # The default duration of time (in minutes) an Anchor lasts when placed 
  duration: 30

renew:
  # How an Anchor can be renewed ("money" or "item")
  method: money
  # The cost to add time to an Anchor
  price: 50
  # The item that is needed to add time to an Anchor (set to a value from this list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)
  item: QUARTZ

# Spooky controls (don't change)
version: 1.0
debug: true
